In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/European_Bank_Processed.csv")

print("Shape:", df.shape)
df.head()

Shape: (10000, 16)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,AgeGroup,CreditScoreBand,TenureGroup,BalanceSegment,EngagementStatus
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,30-45,Medium,New,Zero-balance,Active
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,30-45,Medium,New,Low-balance,Active
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,30-45,Low,Long-term,High-balance,Inactive
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,30-45,Medium,New,Zero-balance,Inactive
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,30-45,High,New,High-balance,Active

In [2]:
geography_summary = (
    df.groupby("Geography")["Exited"]
      .agg(["count", "sum", "mean"])
      .reset_index()
)

geography_summary["ChurnRate"] = geography_summary["mean"] * 100

geography_summary = geography_summary.drop(columns="mean")

geography_summary

  Geography  count  sum  ChurnRate
0    France   5014  810  16.154767
1   Germany   2509  814  32.443204
2     Spain   2477  413  16.673395

In [3]:
age_summary = (
    df.groupby("AgeGroup")["Exited"]
      .agg(["count", "sum", "mean"])
      .reset_index()
)

age_summary["ChurnRate"] = age_summary["mean"] * 100

age_summary = age_summary.drop(columns="mean")

age_summary

  AgeGroup  count  sum  ChurnRate
0    30-45   6248  956  15.300896
1    46-60   1647  842  51.123254
2      60+    464  115  24.784483
3      <30   1641  124   7.556368

In [4]:
age_order = ["<30", "30-45", "46-60", "60+"]

age_summary["AgeGroup"] = pd.Categorical(
    age_summary["AgeGroup"],
    categories=age_order,
    ordered=True
)

age_summary = age_summary.sort_values("AgeGroup")

age_summary

  AgeGroup  count  sum  ChurnRate
3      <30   1641  124   7.556368
0    30-45   6248  956  15.300896
1    46-60   1647  842  51.123254
2      60+    464  115  24.784483

In [5]:
credit_summary = (
    df.groupby("CreditScoreBand")["Exited"]
      .agg(["count", "sum", "mean"])
      .reset_index()
)

credit_summary["ChurnRate"] = credit_summary["mean"] * 100

credit_summary = credit_summary.drop(columns="mean")

credit_order = ["Low", "Medium", "High"]

credit_summary["CreditScoreBand"] = pd.Categorical(
    credit_summary["CreditScoreBand"],
    categories=credit_order,
    ordered=True
)

credit_summary = credit_summary.sort_values("CreditScoreBand")

credit_summary

  CreditScoreBand  count  sum  ChurnRate
1             Low   2534  556  21.941594
2          Medium   5003  981  19.608235
0            High   2463  500  20.300447

In [6]:
tenure_summary = (
    df.groupby("TenureGroup")["Exited"]
      .agg(["count", "sum", "mean"])
      .reset_index()
)

tenure_summary["ChurnRate"] = tenure_summary["mean"] * 100

tenure_summary = tenure_summary.drop(columns="mean")

tenure_order = ["New", "Mid-term", "Long-term"]

tenure_summary["TenureGroup"] = pd.Categorical(
    tenure_summary["TenureGroup"],
    categories=tenure_order,
    ordered=True
)

tenure_summary = tenure_summary.sort_values("TenureGroup")

tenure_summary

  TenureGroup  count  sum  ChurnRate
2         New   3505  741  21.141227
1    Mid-term   3996  785  19.644645
0   Long-term   2499  511  20.448179

In [7]:
balance_summary = (
    df.groupby("BalanceSegment")["Exited"]
      .agg(["count", "sum", "mean"])
      .reset_index()
)

balance_summary["ChurnRate"] = balance_summary["mean"] * 100

balance_summary = balance_summary.drop(columns="mean")

balance_order = [
    "Zero-balance",
    "Low-balance",
    "High-balance"
]

balance_summary["BalanceSegment"] = pd.Categorical(
    balance_summary["BalanceSegment"],
    categories=balance_order,
    ordered=True
)

balance_summary = balance_summary.sort_values("BalanceSegment")

balance_summary

  BalanceSegment  count   sum  ChurnRate
2   Zero-balance   3617   500  13.823611
1    Low-balance   1383   288  20.824295
0   High-balance   5000  1249  24.980000

In [8]:
geography_summary["ChurnContribution"] = (
    geography_summary["sum"] / df["Exited"].sum() * 100
)

geography_summary

  Geography  count  sum  ChurnRate  ChurnContribution
0    France   5014  810  16.154767          39.764359
1   Germany   2509  814  32.443204          39.960727
2     Spain   2477  413  16.673395          20.274914

In [9]:
age_summary["ChurnContribution"] = (
    age_summary["sum"] / df["Exited"].sum() * 100
)

age_summary

  AgeGroup  count  sum  ChurnRate  ChurnContribution
3      <30   1641  124   7.556368           6.087383
0    30-45   6248  956  15.300896          46.931762
1    46-60   1647  842  51.123254          41.335297
2      60+    464  115  24.784483           5.645557

In [10]:
credit_summary["ChurnContribution"] = (
    credit_summary["sum"] / df["Exited"].sum() * 100
)

credit_summary

  CreditScoreBand  count  sum  ChurnRate  ChurnContribution
1             Low   2534  556  21.941594          27.295042
2          Medium   5003  981  19.608235          48.159057
0            High   2463  500  20.300447          24.545901

In [11]:
tenure_summary["ChurnContribution"] = (
    tenure_summary["sum"] / df["Exited"].sum() * 100
)

tenure_summary

  TenureGroup  count  sum  ChurnRate  ChurnContribution
2         New   3505  741  21.141227          36.377025
1    Mid-term   3996  785  19.644645          38.537064
0   Long-term   2499  511  20.448179          25.085911

In [12]:
balance_summary["ChurnContribution"] = (
    balance_summary["sum"] / df["Exited"].sum() * 100
)

balance_summary

  BalanceSegment  count   sum  ChurnRate  ChurnContribution
2   Zero-balance   3617   500  13.823611          24.545901
1    Low-balance   1383   288  20.824295          14.138439
0   High-balance   5000  1249  24.980000          61.315660

In [13]:
segment_priority = pd.DataFrame({
    "SegmentType": [
        "Geography",
        "Age",
        "Credit Score",
        "Tenure",
        "Balance"
    ],
    "HighestRiskSegment": [
        "Germany",
        "46-60",
        "Low",
        "New",
        "High-balance"
    ],
    "HighestChurnRate": [
        geography_summary["ChurnRate"].max(),
        age_summary["ChurnRate"].max(),
        credit_summary["ChurnRate"].max(),
        tenure_summary["ChurnRate"].max(),
        balance_summary["ChurnRate"].max()
    ]
})

segment_priority

    SegmentType HighestRiskSegment  HighestChurnRate
0     Geography            Germany         32.443204
1           Age              46-60         51.123254
2  Credit Score                Low         21.941594
3        Tenure                New         21.141227
4       Balance       High-balance         24.980000

In [14]:
segment_priority.to_csv(
    "../outputs/tables/segment_priority_summary.csv",
    index=False
)

segment_priority

    SegmentType HighestRiskSegment  HighestChurnRate
0     Geography            Germany         32.443204
1           Age              46-60         51.123254
2  Credit Score                Low         21.941594
3        Tenure                New         21.141227
4       Balance       High-balance         24.980000